# Generated by Django 6.0.5 on 2026-05-30 09:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_url', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Đang chờ xử lý'), ('PROCESSING', 'Đang tạo Video'), ('SUCCESS', 'Hoàn tất'), ('FAILED', 'Thất bại')], default='PENDING', max_length=20)),
                ('final_video_path', models.CharField(blank=True, max_length=500, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
