# Generated by Django 6.0.5 on 2026-05-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='script_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Kịch bản AI (JSON)'),
        ),
    ]
